#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re

# Read the original English file
with open('data/html/price_super_market_15102025.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Update language attribute
content = content.replace('lang="en"', 'lang="zh-TW"')

# Update last week link to Chinese version
content = content.replace(
    'href="price_super_market_08102025.html"',
    'href="price_super_market_08102025_chinese.html"'
)

# Translate visible text only (not in HTML tags, CSS, or JavaScript)
# Define translations for text content
text_replacements = [
    # Navigation
    (r'>Weekly Price Comparison<', '>每週價格比較<'),
    (r'>Last Week<', '>上週<'),
    (r'>This Week<', '>本週<'),
    (r'>About<', '>關於<'),
    (r'Buy me a coffee', '請我喝咖啡'),

    # Hero section
    (r'>Smart Price Comparison<', '>智能價格比較<'),
    (r'AI-powered analysis comparing Coles vs Woolworths weekly deals', 'AI驅動分析比較Coles與Woolworths每週優惠'),

    # Retailer section
    (r'>Head-to-Head Price Battle<', '>價格對決<'),
    (r'Coles wins with (\d+) cheaper products', r'Coles以\1個更便宜商品獲勝'),
    (r'Woolworths wins with (\d+) cheaper products', r'Woolworths以\1個更便宜商品獲勝'),

    # Stats
    (r'>Weekly Analysis<', '>每週分析<'),
    (r'>Products Compared<', '>已比較商品<'),
    (r'>Total Savings Identified<', '>總計節省已識別<'),
    (r'>Coles Best Deals<', '>Coles最佳優惠<'),
    (r'>Woolworths Best Deals<', '>Woolworths最佳優惠<'),
    (r'>Average Savings<', '>平均節省<'),
    (r'>Best Deals Found<', '>發現最佳優惠<'),

    # Product comparison
    (r'>Product Price Comparisons<', '>商品價格比較<'),
    (r'>Product<', '>商品<'),
    (r'>Store<', '>超市<'),
    (r'>Price<', '>價格<'),
    (r'>Category<', '>類別<'),

    # Special types and badges
    (r'>HALF_PRICE<', '>半價<'),
    (r'>Half Price<', '>半價<'),
    (r'>Special<', '>特價<'),
    (r'BEST DEAL - Save', '最佳優惠 - 節省'),
    (r'>Save<', '>節省<'),

    # Product details
    (r'General • Similarity:', '一般 • 相似度:'),

    # Footer
    (r'AI-Powered Price Comparison', 'AI驅動價格比較'),
    (r'Generated by AdvGen Price Comparer', '由AdvGen價格比較器生成'),
    (r'Data sourced from official Coles and Woolworths catalogues - Week', '數據來源於Coles和Woolworths官方目錄 - 週'),
    (r'>Home<', '>首頁<'),
    (r'>GitHub<', '>GitHub<'),
    (r'>Contact<', '>聯繫<'),
]

# Apply all replacements
for pattern, replacement in text_replacements:
    content = re.sub(pattern, replacement, content)

# Save the translated file
with open('data/html/price_super_market_15102025_chinese.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Successfully created data/html/price_super_market_15102025_chinese.html")
print("  - Changed language to zh-TW")
print("  - Updated last week link to price_super_market_08102025_chinese.html")
print(f"  - Applied {len(text_replacements)} translation rules")
print("  - CSS classes and brand names preserved")
