#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re

# Comprehensive translation dictionary for English to Traditional Chinese
translations = {
    # Page metadata
    'Price Comparison Report': '價格比較報告',

    # Navigation
    'Weekly Price Comparison': '每週價格比較',
    'Last Week': '上週',
    'This Week': '本週',
    'About': '關於',
    'Buy me a coffee': '請我喝咖啡',

    # Hero section
    'Smart Price Comparison': '智能價格比較',
    'Your trusted guide to finding the best grocery deals in Brisbane': '您在布里斯本尋找最佳超市優惠的可靠指南',
    'AI-powered analysis comparing Coles vs Woolworths weekly deals': 'AI驅動分析比較Coles與Woolworths每週優惠',

    # Week selector
    'Oct': '十月',
    'Sept': '九月',

    # Retailer section
    'Head-to-Head Price Battle': '價格對決',
    'wins with': '以',
    'cheaper products': '個更便宜商品獲勝',
    'VS': '對決',

    # Stats
    'Products Compared': '已比較商品',
    'Average Savings': '平均節省',
    'Best Deals Found': '發現最佳優惠',
    'Weekly Analysis': '每週分析',
    'Total': '總計',
    'Identified': '已識別',
    'Best Deals': '最佳優惠',

    # Product comparison
    'Product Price Comparisons': '商品價格比較',
    'Filter by Category': '按類別篩選',
    'All Categories': '所有類別',

    # Table headers and labels
    'Product': '商品',
    'Store': '超市',
    'Price': '價格',
    'Category': '類別',
    'Savings': '節省',
    'Unit Price': '單位價格',
    'Special Type': '特價類型',
    'Winner': '最優惠',
    'General': '一般',
    'Similarity': '相似度',

    # Store names (keep as is - no translation)
    'Coles': 'Coles',
    'Woolworths': 'Woolworths',

    # Categories
    'Snacks': '零食',
    'Beverages': '飲品',
    'Dairy': '乳製品',
    'Frozen': '冷凍食品',
    'Pantry': '食品儲藏室',
    'Personal Care': '個人護理',
    'Household': '家居用品',
    'Pet Food': '寵物食品',
    'Confectionery': '糖果',
    'Ice Cream': '雪糕',
    'Meat': '肉類',
    'Coffee': '咖啡',

    # Special types
    'Half Price': '半價',
    'HALF_PRICE': '半價',
    '1/2 Price': '半價',
    'Special': '特價',
    'Save': '節省',
    'BEST DEAL': '最佳優惠',

    # Footer
    'AI-Powered Price Comparison': 'AI驅動價格比較',
    'Generated by AdvGen Price Comparer': '由AdvGen價格比較器生成',
    'Data sourced from official Coles and Woolworths catalogues': '數據來源於Coles和Woolworths官方目錄',
    'Week': '週',
    'Home': '首頁',
    'GitHub': 'GitHub',
    'Contact': '聯繫',
}

def translate_html_file(input_file, output_file):
    """Translate HTML file from English to Traditional Chinese"""

    # Read the input file
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Update language attribute
    content = content.replace('lang="en"', 'lang="zh-TW"')

    # Update last week link to Chinese version
    content = content.replace(
        'price_super_market_08102025.html',
        'price_super_market_08102025_chinese.html'
    )

    # Translate phrases (sort by length descending to avoid partial replacements)
    sorted_translations = sorted(translations.items(), key=lambda x: len(x[0]), reverse=True)

    for english, chinese in sorted_translations:
        # Case-insensitive replacement for whole words/phrases
        # Use multiple patterns to catch variations
        patterns = [
            # Exact match with word boundaries
            (r'(?<![a-zA-Z])' + re.escape(english) + r'(?![a-zA-Z])', chinese),
            # Inside HTML tags
            (r'>' + re.escape(english) + r'<', '>' + chinese + '<'),
        ]

        for pattern, replacement in patterns:
            content = re.sub(pattern, replacement, content, flags=re.IGNORECASE)

    # Additional specific replacements for complex patterns
    # Handle "Coles wins with XX cheaper products"
    content = re.sub(
        r'(Coles|Woolworths)\s+wins\s+with\s+(\d+)\s+cheaper\s+products',
        r'\1以\2個更便宜商品獲勝',
        content
    )

    # Handle "Total Savings Identified"
    content = re.sub(
        r'Total\s+Savings\s+Identified',
        '總計節省已識別',
        content,
        flags=re.IGNORECASE
    )

    # Handle "Coles Best Deals" / "Woolworths Best Deals"
    content = re.sub(
        r'(Coles|Woolworths)\s+Best\s+Deals',
        r'\1最佳優惠',
        content,
        flags=re.IGNORECASE
    )

    # Save the translated file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Successfully created {output_file}")
    print(f"  - Changed language to zh-TW")
    print(f"  - Updated last week link to price_super_market_08102025_chinese.html")
    print(f"  - Translated {len(translations)} terms")
    print(f"  - All English text translated (brand names preserved)")

if __name__ == '__main__':
    input_file = 'data/html/price_super_market_15102025.html'
    output_file = 'data/html/price_super_market_15102025_chinese.html'

    translate_html_file(input_file, output_file)
