#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re

# Translation dictionary for English to Traditional Chinese
translations = {
    # Page metadata
    'Price Comparison Report': '價格比較報告',

    # Navigation
    'Weekly Price Comparison': '每週價格比較',
    'Last Week': '上週',
    'This Week': '本週',
    'About': '關於',

    # Hero section
    'Smart Price Comparison': '智能價格比較',
    'Your trusted guide to finding the best grocery deals in Brisbane': '您在布里斯本尋找最佳超市優惠的可靠指南',

    # Week selector
    'Oct': '十月',
    'Sept': '九月',

    # Retailer section
    'Head-to-Head Price Battle': '價格對決',

    # Stats
    'Products Compared': '已比較商品',
    'Average Savings': '平均節省',
    'Best Deals Found': '發現最佳優惠',

    # Product comparison
    'Product Price Comparisons': '商品價格比較',
    'Filter by Category': '按類別篩選',
    'All Categories': '所有類別',

    # Table headers
    'Product': '商品',
    'Store': '超市',
    'Price': '價格',
    'Category': '類別',
    'Savings': '節省',
    'Unit Price': '單位價格',
    'Special Type': '特價類型',
    'Winner': '最優惠',

    # Store names
    'Coles': 'Coles',
    'Woolworths': 'Woolworths',

    # Categories
    'Snacks': '零食',
    'Beverages': '飲品',
    'Dairy': '乳製品',
    'Frozen': '冷凍食品',
    'Pantry': '食品儲藏室',
    'Personal Care': '個人護理',
    'Household': '家居用品',
    'Pet Food': '寵物食品',
    'Confectionery': '糖果',
    'Ice Cream': '雪糕',
    'Meat': '肉類',
    'Coffee': '咖啡',

    # Special types
    'Half Price': '半價',
    '1/2 Price': '半價',
    'Special': '特價',
    'Save': '節省',

    # Footer
    'AI-Powered Price Comparison': 'AI驅動價格比較',
    'Generated by AdvGen Price Comparer': '由AdvGen價格比較器生成',
    'Data sourced from official Coles and Woolworths catalogues': '數據來源於Coles和Woolworths官方目錄',
    'Week': '週',
    'Home': '首頁',
    'GitHub': 'GitHub',
    'Contact': '聯繫',
}

def translate_text(text, translations):
    """Replace English text with Traditional Chinese"""
    result = text
    for en, zh in translations.items():
        # Use word boundary for exact matches
        result = re.sub(r'\b' + re.escape(en) + r'\b', zh, result, flags=re.IGNORECASE)
    return result

def translate_html_file(input_file, output_file):
    """Translate HTML file from English to Traditional Chinese"""

    # Read the input file
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Update language attribute
    content = content.replace('lang="en"', 'lang="zh-TW"')

    # Update last week link to Chinese version
    content = content.replace(
        'price_super_market_08102025.html',
        'price_super_market_08102025_chinese.html'
    )

    # Translate common phrases first (longer phrases before shorter ones)
    # Sort by length descending to avoid partial replacements
    sorted_translations = sorted(translations.items(), key=lambda x: len(x[0]), reverse=True)

    for english, chinese in sorted_translations:
        # Match whole words/phrases
        content = re.sub(
            r'(?<![a-zA-Z])' + re.escape(english) + r'(?![a-zA-Z])',
            chinese,
            content
        )

    # Save the translated file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Successfully created {output_file}")
    print(f"  - Changed language to zh-TW")
    print(f"  - Updated last week link to price_super_market_08102025_chinese.html")
    print(f"  - Translated {len(translations)} terms")

if __name__ == '__main__':
    input_file = 'data/html/price_super_market_15102025.html'
    output_file = 'data/html/price_super_market_15102025_chinese.html'

    translate_html_file(input_file, output_file)
