#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re

# Read the original English file
with open('data/html/price_super_market_15102025.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Update language attribute
content = content.replace('lang="en"', 'lang="zh-TW"')

# Update last week link to Chinese version
content = content.replace(
    'href="price_super_market_08102025.html"',
    'href="price_super_market_08102025_chinese.html"'
)

# Translate visible text - use broader patterns
text_replacements = [
    # Page title
    ('Price Comparison Report', '價格比較報告'),

    # Navigation
    ('Weekly Price Comparison', '每週價格比較'),
    ('>Last Week<', '>上週<'),
    ('>This Week<', '>本週<'),
    ('>About<', '>關於<'),
    ('Buy me a coffee', '請我喝咖啡'),

    # Hero section
    ('Smart Price Comparison', '智能價格比較'),
    ('AI-powered analysis comparing Coles vs Woolworths weekly deals', 'AI驅動分析比較Coles與Woolworths每週優惠'),

    # Month names
    (' Oct ', ' 十月 '),
    (' Sept ', ' 九月 '),

    # Retailer section
    ('Head-to-Head Price Battle', '價格對決'),
    ('Coles wins with', 'Coles以'),
    ('Woolworths wins with', 'Woolworths以'),
    ('cheaper products', '個更便宜商品獲勝'),

    # Stats
    ('Weekly Analysis', '每週分析'),
    ('>Products Compared<', '>已比較商品<'),
    ('Total Savings Identified', '總計節省已識別'),
    ('Coles Best Deals', 'Coles最佳優惠'),
    ('Woolworths Best Deals', 'Woolworths最佳優惠'),
    ('>Average Savings<', '>平均節省<'),
    ('>Best Deals Found<', '>發現最佳優惠<'),

    # Product comparison
    ('Product Price Comparisons', '商品價格比較'),
    ('>Product<', '>商品<'),
    ('>Store<', '>超市<'),
    ('>Price<', '>價格<'),
    ('>Category<', '>類別<'),

    # Special types and badges
    ('>HALF_PRICE<', '>半價<'),
    ('HALF_PRICE', '半價'),
    ('>Half Price<', '>半價<'),
    ('>Special<', '>特價<'),
    ('BEST DEAL - Save', '最佳優惠 - 節省'),
    ('>Save<', '>節省<'),
    ('Save ', '節省 '),

    # Product details
    ('General • Similarity:', '一般 • 相似度:'),
    ('Similarity:', '相似度:'),

    # Footer
    ('AI-Powered Price Comparison', 'AI驅動價格比較'),
    ('Generated by AdvGen Price Comparer', '由AdvGen價格比較器生成'),
    ('Data sourced from official Coles and Woolworths catalogues - Week', '數據來源於Coles和Woolworths官方目錄 - 週'),
    ('>Home<', '>首頁<'),
    ('>GitHub<', '>GitHub<'),
    ('>Contact<', '>聯繫<'),
]

# Apply all replacements
for pattern, replacement in text_replacements:
    content = content.replace(pattern, replacement)

# Save the translated file
with open('data/html/price_super_market_15102025_chinese.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Successfully created data/html/price_super_market_15102025_chinese.html")
print("  - Changed language to zh-TW")
print("  - Updated last week link to price_super_market_08102025_chinese.html")
print(f"  - Applied {len(text_replacements)} translation rules")
print("  - CSS classes and brand names preserved")
print("  - All visible English text translated")
