#!/usr/bin/env python3
"""
Translate price_super_market_18032026.html to Traditional Chinese
"""

import re

# Translation dictionary for Traditional Chinese
translations = {
    # Navigation and Header
    "Weekly Price Comparison": "每週價格比較",
    "Last Week": "上週",
    "This Week": "本週",
    "Buy me a Coffee": "請我飲咖啡",
    
    # Hero Section
    "Smart Price Comparison": "智能價格比較",
    "AI-powered analysis comparing Coles vs Woolworths weekly deals": "AI驅動分析比較 Coles 與 Woolworths 每週優惠",
    "March 2026": "2026年3月",
    
    # Retailer Section
    "Head-to-Head Price Battle": "價格對決",
    "wins with": "勝出，擁有",
    "cheaper products": "款更平產品",
    
    # Stats Section
    "Weekly Analysis": "每週分析",
    "Products Compared": "比較產品數量",
    "Total Savings Identified": "已識別總節省金額",
    "Coles Best Deals": "Coles 最佳優惠",
    "Woolworths Best Deals": "Woolworths 最佳優惠",
    
    # Product Comparison Section
    "Product Price Comparisons": "產品價格比較",
    
    # Labels
    "Similarity": "相似度",
    "BEST DEAL": "最抵價",
    "Save": "慳",
    "Half Price": "半價",
    "HALF_PRICE": "半價",
    "Special": "特價",
    "Down Down": "降價",
    "Multi-Buy Special": "多買優惠",
    "From the Fridge": "冷藏",
    
    # Categories
    "General": "一般",
    "Dairy": "乳製品",
    "Drinks": "飲品",
    "Snacks": "零食",
    "Confectionery": "糖果",
    "Frozen": "冷凍",
    "Condiments": "調味料",
    
    # Footer
    "AI-Powered Price Comparison": "AI驅動價格比較",
    "Generated by AdvGen Price Comparer": "由 AdvGen Price Comparer 生成",
    "Data sourced from official Coles and Woolworths catalogues": "數據來自 Coles 及 Woolworths 官方產品目錄",
    "Home": "主頁",
    "GitHub": "GitHub",
    
    # Months for date conversion
    "January": "1月",
    "February": "2月",
    "March": "3月",
    "April": "4月",
    "May": "5月",
    "June": "6月",
    "July": "7月",
    "August": "8月",
    "September": "9月",
    "October": "10月",
    "November": "11月",
    "December": "12月",
}

def translate_html(input_file, output_file):
    """Translate HTML content to Traditional Chinese"""
    
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Change HTML lang attribute
    content = content.replace('<html lang="en">', '<html lang="zh-Hant">')
    
    # Translate title
    content = content.replace(
        '<title>Price Comparison Report | Coles vs Woolworths | 2026-03-17</title>',
        '<title>價格比較報告 | Coles 對 Woolworths | 2026年3月17日</title>'
    )
    
    # Translate text content (prioritize longer phrases first)
    sorted_translations = sorted(translations.items(), key=lambda x: len(x[0]), reverse=True)
    
    for english, chinese in sorted_translations:
        # Use word boundaries for better matching where appropriate
        if english in ["Coles", "Woolworths"]:
            continue  # Skip brand names
        content = content.replace(english, chinese)
    
    # Translate winner announcement pattern
    content = re.sub(
        r'Woolworths wins with (\d+) cheaper products',
        r'Woolworths 勝出，擁有\1款更平產品',
        content
    )
    content = re.sub(
        r'Coles wins with (\d+) cheaper products',
        r'Coles 勝出，擁有\1款更平產品',
        content
    )
    
    # Translate BEST DEAL patterns
    content = re.sub(
        r'BEST DEAL - Save \$(\d+\.?\d*)',
        r'最抵價 - 慳 \$\1',
        content
    )
    
    # Translate date ranges like "11-17 March 2026"
    content = re.sub(
        r'(\d+)-(\d+) March 2026',
        r'2026年3月\1日至\2日',
        content
    )
    content = re.sub(
        r'(\d+)-(\d+) April 2026',
        r'2026年4月\1日至\2日',
        content
    )
    
    # Fix date ranges that got partially translated
    content = re.sub(
        r'(\d+)-(\d+) 2026年3月',
        r'2026年3月\1日至\2日',
        content
    )
    
    # Translate footer date text
    content = content.replace(
        'Data sourced from official Coles and Woolworths catalogues - Week 1-7 Oct 2025',
        '數據來自 Coles 及 Woolworths 官方產品目錄 - 2025年10月第1至7週'
    )
    
    # Translate any remaining English text in footer
    content = re.sub(
        r'Week (\d+)-(\d+) Oct (\d+)',
        r'\3年10月第\1至\2週',
        content
    )
    
    # Translate product details pattern "Category • Similarity: XX%"
    content = re.sub(
        r'General • Similarity: (\d+\.?\d*)%',
        r'一般 • 相似度：\1%',
        content
    )
    content = re.sub(
        r'Dairy • Similarity: (\d+\.?\d*)%',
        r'乳製品 • 相似度：\1%',
        content
    )
    content = re.sub(
        r'Drinks • Similarity: (\d+\.?\d*)%',
        r'飲品 • 相似度：\1%',
        content
    )
    content = re.sub(
        r'Snacks • Similarity: (\d+\.?\d*)%',
        r'零食 • 相似度：\1%',
        content
    )
    content = re.sub(
        r'Confectionery • Similarity: (\d+\.?\d*)%',
        r'糖果 • 相似度：\1%',
        content
    )
    content = re.sub(
        r'Frozen • Similarity: (\d+\.?\d*)%',
        r'冷凍 • 相似度：\1%',
        content
    )
    content = re.sub(
        r'Condiments • Similarity: (\d+\.?\d*)%',
        r'調味料 • 相似度：\1%',
        content
    )
    
    # Save the translated file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print("Translation complete!")
    print("   Input:  {}".format(input_file))
    print("   Output: {}".format(output_file))

if __name__ == "__main__":
    input_file = "data/html/price_super_market_18032026.html"
    output_file = "data/html/price_super_market_18032026_chinese.html"
    
    translate_html(input_file, output_file)
