import re

# Read the source file
with open('data/html/price_super_market_11022026.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Translation mappings
translations = {
    # Title and meta
    '<html lang="en">': '<html lang="zh-TW">',
    '<title>Price Comparison Report | Coles vs Woolworths | 2026-02-10</title>': '<title>價格比較報告 | Coles vs Woolworths | 2026-02-10</title>',

    # Header
    'Weekly Price Comparison': '每週價格比較',
    'Last Week': '上週',
    'This Week': '本週',
    'Buy me a Coffee': '請我喝咖啡',

    # Hero section
    '🛒 Smart Price Comparison': '🛒 智能價格比較',
    'AI-powered analysis comparing Coles vs Woolworths weekly deals': 'AI智能分析 比較Coles與Woolworths每週優惠',

    # Retailer section
    '🏆 Head-to-Head Price Battle': '🏆 價格對決',
    'Woolworths wins with 49 cheaper products': 'Woolworths勝出 共49件商品價格較低',

    # Stats section
    '📊 Weekly Analysis': '📊 每週分析',
    'Products Compared': '比較商品數量',
    'Total Savings Identified': '已發現總節省金額',
    'Coles Best Deals': 'Coles最佳優惠',
    'Woolworths Best Deals': 'Woolworths最佳優惠',

    # Product comparison section
    'Product Price Comparisons': '商品價格比較',

    # Store names in cards
    '>Woolworths<': '>Woolworths<',
    '>Coles<': '>Coles<',

    # Badges and labels
    'BEST DEAL - Save': '最優惠 - 省',
    'Half Price Specials': '半價特惠',
    'HALF_PRICE': '半價',
    'Down Down': '減價',
    'Multi-Buy Special': '多買優惠',

    # Category labels
    'General •': '一般 •',
    'Frozen •': '冷凍 •',
    'Drinks •': '飲料 •',
    'Snacks •': '零食 •',
    'Dairy •': '乳製品 •',
    'Condiments •': '調味品 •',
    'Meat & Seafood •': '肉類海鮮 •',

    'Similarity:': '相似度:',

    # Footer
    'AI-Powered Price Comparison | Generated by AdvGen Price Comparer': 'AI智能價格比較 | 由AdvGen Price Comparer生成',
    'Data sourced from official Coles and Woolworths catalogues - Week 1-7 Oct 2025': '數據來源自Coles及Woolworths官方目錄 - 2026年2月11-17日',
    'Home': '首頁',
    'GitHub': 'GitHub',
}

# Apply translations
for eng, chi in translations.items():
    content = content.replace(eng, chi)

# Update the link to Chinese version
content = content.replace(
    'href="price_super_market_04022026.html"',
    'href="price_super_market_04022026_Chinese.html"'
)

# Write the translated file
with open('data/html/price_super_market_11022026_Chinese.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation completed! File saved to data/html/price_super_market_11022026_Chinese.html")
