#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re

# Read source HTML
with open('data/html/price_super_market_26112025.html', 'r', encoding='utf-8') as f:
    html = f.read()

# Comprehensive translation dictionary
translations = {
    # Title and meta
    'Price Comparison Report': '價格比較報告',

    # Navigation
    'Last Week': '上週',
    'This Week': '本週',
    'Weekly Price Comparison': '每週價格比較',
    'Home': '首頁',

    # Hero section
    'Smart Price Comparison': '智能價格比較',
    'AI-powered analysis comparing Coles vs Woolworths weekly deals': 'AI驅動分析比較Coles與Woolworths每週優惠',
    'Head-to-Head Price Battle': '正面價格對決',

    # Stats
    'Total Items': '總商品數',
    'Best Deals': '最佳優惠',
    'Half Price Specials': '半價特價',
    'Avg. Savings': '平均節省',

    # Deal badges
    'HALF PRICE': '半價',
    'GOOD VALUE': '超值',
    'BEST DEAL': '最佳優惠',
    'HOT DEAL': '熱賣',
    'BETTER VALUE': '更優惠',
    'CHRISTMAS SPECIAL': '聖誕特價',

    # Price terms
    'Save $': '節省 $',
    'per kg': '每公斤',
    'per 100g': '每100克',
    'per 100ml': '每100毫升',
    'per litre': '每公升',
    'per each': '每個',

    # Footer
    'AI-Powered Price Comparison': 'AI驅動價格比較',
    'Generated by AdvGen Price Comparer': '由AdvGen價格比較器生成',
    'Data sourced from official Coles and Woolworths catalogues': '數據來自Coles和Woolworths官方目錄',
    'Buy me a Coffee': '請我喝咖啡',
}

# Apply translations carefully - only to text content, not HTML/CSS/JS
def safe_replace(html_content, old, new):
    # Only replace in visible text content, not in attributes or code
    # Match text between > and <
    pattern = r'(>[^<]*?)' + re.escape(old) + r'([^>]*?<)'
    replacement = r'\1' + new + r'\2'
    return re.sub(pattern, replacement, html_content, flags=re.IGNORECASE)

for english, chinese in translations.items():
    html = safe_replace(html, english, chinese)

# Specific replacements
html = re.sub(r'<title>[^<]*</title>', '<title>價格比較報告 | Coles vs Woolworths | 2025年11月25日</title>', html)

# Fix navigation links text
html = re.sub(r'>Last Week<', '>上週<', html)
html = re.sub(r'>This Week<', '>本週<', html)
html = re.sub(r'>Weekly Price Comparison<', '>每週價格比較<', html)

# Write output
with open('data/html/price_super_market_26112025_chinese.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Translation completed!")
print("Created: data/html/price_super_market_26112025_chinese.html")
