import re

# Read the source file
with open(r'C:\Users\advgen10\source\repos\AdvGenPriceComparer\data\html\price_super_market_18022026.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Translation mappings
translations = {
    # HTML attributes
    '<html lang="en">': '<html lang="zh-TW">',

    # Title
    'Price Comparison Report | Coles vs Woolworths | 2026-02-17': '價格比較報告 | Coles vs Woolworths | 2026-02-17',

    # Header
    'Weekly Price Comparison': '每週價格比較',
    '>Last Week<': '>上週<',
    '>This Week<': '>本週<',
    '>Buy me a Coffee<': '>請我喝咖啡<',

    # Hero section
    '🛒 Smart Price Comparison': '🛒 智能價格比較',
    'AI-powered analysis comparing Coles vs Woolworths weekly deals': 'AI智能分析 比較Coles與Woolworths每週優惠',

    # Week selector - update links to chinese versions
    'price_super_market_11022026.html': 'price_super_market_11022026_chinese.html',

    # Retailer section
    '🏆 Head-to-Head Price Battle': '🏆 價格對決',
    'Woolworths wins with 38 cheaper products': 'Woolworths勝出 共38件商品價格較低',

    # Stats section
    '📊 Weekly Analysis': '📊 每週分析',
    'Products Compared': '比較商品數量',
    'Total Savings Identified': '已發現總節省金額',
    'Coles Best Deals': 'Coles最佳優惠',
    'Woolworths Best Deals': 'Woolworths最佳優惠',

    # Product section
    '>Product Price Comparisons<': '>商品價格比較<',

    # Categories
    'General • Similarity': '一般 • 相似度',
    'Frozen • Similarity': '冷凍 • 相似度',
    'Confectionery • Similarity': '糖果零食 • 相似度',
    'Condiments • Similarity': '調味料 • 相似度',
    'Meat & Seafood • Similarity': '肉類及海鮮 • 相似度',
    'Dairy • Similarity': '乳製品 • 相似度',
    'Bakery • Similarity': '烘焙 • 相似度',
    'Drinks • Similarity': '飲料 • 相似度',
    'Pantry • Similarity': '食品櫃 • 相似度',
    'Health & Beauty • Similarity': '保健及美容 • 相似度',
    'Household • Similarity': '家居用品 • 相似度',
    'Baby • Similarity': '嬰兒用品 • 相似度',
    'Pet • Similarity': '寵物用品 • 相似度',
    'Liquor • Similarity': '酒類 • 相似度',

    # Badges
    '>HALF_PRICE<': '>半價<',
    '>Half Price Specials<': '>半價特惠<',
    '>Special<': '>特價<',

    # Footer
    'AI-Powered Price Comparison | Generated by AdvGen Price Comparer': 'AI智能價格比較 | 由AdvGen Price Comparer生成',
    'Data sourced from official Coles and Woolworths catalogues - Week 1-7 Oct 2025': '資料來源於Coles和Woolworths官方目錄 - 2026年2月18-24日',
    '>Home<': '>首頁<',
}

# Apply translations
for eng, chi in translations.items():
    content = content.replace(eng, chi)

# Handle "BEST DEAL - Save $X.XX" pattern
content = re.sub(r'BEST DEAL - Save \$', '最優惠 - 省 $', content)

# Write the output file
with open(r'C:\Users\advgen10\source\repos\AdvGenPriceComparer\data\html\price_super_market_18022026_chinese.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation complete! Output saved to price_super_market_18022026_chinese.html")
